=== DashyNMS/sensor-definitions/schemas/index-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "DashyNMS schema-1 OS shard index",
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "catalogueVersion", "shards", "notices"],
  "properties": {
    "schemaVersion": { "const": 1 },
    "catalogueVersion": { "type": "string", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$" },
    "notices": { "$ref": "#/$defs/asset" },
    "shards": {
      "type": "array",
      "maxItems": 10000,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["os", "sha256", "downloadBytes", "expandedBytes", "definitions"],
        "properties": {
          "os": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$" },
          "sha256": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
          "downloadBytes": { "type": "integer", "minimum": 1, "maximum": 524288 },
          "expandedBytes": { "type": "integer", "minimum": 1, "maximum": 2097152 },
          "definitions": { "type": "integer", "minimum": 1 }
        }
      }
    }
  },
  "$defs": {
    "asset": {
      "type": "object",
      "additionalProperties": false,
      "required": ["sha256", "downloadBytes"],
      "properties": {
        "sha256": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
        "downloadBytes": { "type": "integer", "minimum": 1, "maximum": 1048576 }
      }
    }
  }
}

=== DashyNMS/sensor-definitions/feeds/v1/stable.json
{"catalogueVersion":"1.0.0","notices":{"downloadBytes":35467,"sha256":"d28c777b70137c0052ce328a0f9644ab4ae14bfd38b19517e6fff62a74c19ec2"},"schemaVersion":1,"shards":[{"definitions":13,"downloadBytes":1599,"expandedBytes":11544,"os":"acano","sha256":"55c15b3e6a5b5a0bfa24d0c04c1dc78fe2d69129967162e79e3c07a501d0b181"},{"definitions":4,"downloadBytes":671,"expandedBytes":2696,"os":"acos","sha256":"4f2b7bc081edb2b19c5803f6eb4c92c0c4e8e0a0e182a9cf27c622212b00f986"},{"definitions":13,"downloadBytes":1595,"expandedBytes":11492,"os":"acs","sha256":"d9990481ac131ad45f4433bc7d506eafed7ba2c33f461e16fd1a796f94a5b4d7"},{"definitions":13,"downloadBytes":1598,"expandedBytes":11518,"os":"acsw","sha256":"9d841703ff5da90f6b6705536586c61f1e6e937ebe85a7591048f55d57d1d109"},{"definitions":1,"downloadBytes":4142,"expandedBytes":24344,"os":"adva-aos","sha256":"dd2c59bfc585fe497166104ebaa3e21566f1797ddd5d47454d0909c87f62bfc6"},{"definitions":8,"downloadBytes":1167,"expandedBytes":6500,"os":"adva_fsp150","sha256":"b762051c927f286f066a04cdd349fd5b488ce01deadad6bb57aeb1f498019b0e"},{"definitions":5,"downloadBytes":554,"expandedBytes":2751,"os":"advantech","sha256":"76dc95f033bb84bea755852852d3cf864b72191f2232c3441a52e63eff3a2bab"},{"definitions":1,"downloadBytes":424,"expandedBytes":808,"os":"airos","sha256":"d583d65c05e9edda4bbfe44d3a9bd3abdfbdd4a5694472e25867dce9f760b1a2"},{"definitions":1,"downloadBytes":515,"expandedBytes":1329,"os":"airos-af","sha256":"b5d28353c9761fcbceda796f080e71959a26c13ad1051151b56fa208f14784e8"},{"definitions":2,"downloadBytes":490,"expandedBytes":1291,"os":"airos-af-ltu","sha256":"cf314dbe2cc96db9c0eba77efad5e571ff7c3f347a05553fcb5570c7218a4118"},{"definitions":2,"downloadBytes":480,"expandedBytes":1252,"os":"airos-af60","sha256":"43c59ec0819f0a2c623a7ae5c6403153c6782954349561c4eff3dc4797d38bca"},{"definitions":2,"downloadBytes":482,"expandedBytes":1397,"os":"akcp","sha256":"f14180b578c46e3614e80ce4433a89430e486f11c15b8e21a425f17717aa07aa"},{"definitions":44,"downloadBytes":960,"expandedBytes":26359,"os":"alaxala","sha256":"64af683ceda8cf3f01c464108bbee88173412db5924e5496b078c48574efd64e"},{"definitions":10,"downloadBytes":857,"expandedBytes":5560,"os":"albentiaaos","sha256":"bd0db154300406bd3bd42ba2168c46227e7a0fd09bd0172da616866b2726c632"},{"definitions":7,"downloadBytes":739,"expandedBytes":3744,"os":"algcom-dc-ups","sha256":"bdb2c70610669cfde9e4607d304cd93325f6d46d8111bc45bee15346a6bc3c98"},{"definitions":2,"downloadBytes":474,"expandedBytes":1222,"os":"aloha","sha256":"e61b1318715c4b3e811d20c035c64f1cc7d5cce75cd8f015ac0a85cf23842203"},{"definitions":7,"downloadBytes":758,"expandedBytes":3902,"os":"alpha-power","sha256":"b1085456940a0688b5a484bf775ad98152245170aa11683ea631285fd5c75184"},{"definitions":17,"downloadBytes":911,"expandedBytes":8509,"os":"alpineoe-tdcmedfa","sha256":"02a69bac83454b36bf6311ea21930fb8fe80770723b51c15e410c54c17926d5f"},{"definitions":2,"downloadBytes":508,"expandedBytes":1680,"os":"aos","sha256":"f5730f06083d44b373c09a87ea627da3914a505cd6997888865aeda3d0295d09"},{"definitions":4,"downloadBytes":756,"expandedBytes":3265,"os":"aos6","sha256":"035b55d1a31dba728ba5bc985c6c1901e1345f32231da3a5a35b7a7259560cc3"},{"definitions":7,"downloadBytes":1068,"expandedBytes":5757,"os":"aos7","sha256":"da3193fbd12c059e3e4cfa4bbd8327e9055ab2f1414b4d62ecf0504a994d0d88"},{"definitions":41,"downloadBytes":2693,"expandedBytes":25569,"os":"apc","sha256":"739de140d92432bfc549f0a4c0e82e384a9ed0ff35df098c7df3c9cac0fb8577"},{"definitions":3,"downloadBytes":566,"expandedBytes":2280,"os":"apc-cpdu","sha256":"c264402116e9fb43e5951134438622e61aa632714d1401f9b11259d59b51c377"},{"definitions":5,"downloadBytes":629,"expandedBytes":2950,"os":"apc-inrow","sha256":"528164591d5e2017a9a7fc03543b840ff37278e1456096b4868b3827840d0a83"},{"definitions":12,"downloadBytes":847,"expandedBytes":6039,"os":"apc-mgeups","sha256":"d643f4662736bfb37f76eec21ecdbc6ef9330fe9efa1b3f8358132dcab2ed011"},{"definitions":1,"downloadBytes":452,"expandedBytes":853,"os":"apc-netbotz","sha256":"1e1bc3cea2c090fe61b2c105a5cb45e9f10db7334b3d847a91eae8d789fbd8f3"},{"definitions":13,"downloadBytes":1598,"expandedBytes":11518,"os":"apic","sha256":"19428acf588ffeb3a7a951a2c6ff3d0a7fff41b3bc9393ff19ebcc60fb13e9c4"},{"definitions":16,"downloadBytes":904,"expandedBytes":11641,"os":"arris-apex","sha256":"6b8f28968a7578dbd3d20cc0abcedc21369c5ac794073fd7c8f8d474c1c7e321"},{"definitions":7,"downloadBytes":550,"expandedBytes":3566,"os":"arris-c3","sha256":"76c9e4ba6aaf8971dbf148dad88309821016d457b80c00e60fd2910b0bf40c69"},{"definitions":1,"downloadBytes":432,"expandedBytes":813,"os":"arris-dsr4410md","sha256":"95c31da31a69f3fd9c78662365e17ab9883f61d66d5cbfe1bb0757e1bf1ffbe7"},{"definitions":2,"downloadBytes":462,"expandedBytes":1205,"os":"aruba-instant","sha256":"cd176cdc0fa5c10b19a81760755f375c602cdde0eff93dc7485a45922bfbbc9f"},{"definitions":9,"downloadBytes":1175,"expandedBytes":7138,"os":"arubaos-cx","sha256":"ef269085be3aab2a4415a0e51f681788726dd9f8aea33ea6068cde7a8e019e5c"},{"definitions":16,"downloadBytes":1815,"expandedBytes":13239,"os":"asa","sha256":"bc3815c278cde009c36c36a2519dbd4be69d943b8238bcc52f3ce01d23e01878"},{"definitions":3,"downloadBytes":497,"expandedBytes":1685,"os":"ats","sha256":"a32f2ca1707f7cd45afc8c040af6a8819b959a7643f6e23649997a0ebcb0dc1f"},{"definitions":9,"downloadBytes":1313,"expandedBytes":8037,"os":"audiocodes","sha256":"ce65da1864c06140640844b86e49cdff16dc67d5fa7ad4e2b5e3e03cf37619b9"},{"definitions":1,"downloadBytes":519,"expandedBytes":1401,"os":"aviat-wtm","sha256":"b9d7c6dc43c8545ca4ecd3d00d6a29824100de7e81ca5983bca00c632ffd3e5d"},{"definitions":7,"downloadBytes":725,"expandedBytes":5063,"os":"avocent","sha256":"49e576cf326ee0a62ddd7b1a9a62c0840d5720565d9fd9edd3fe56a6622fac81"},{"definitions":5,"downloadBytes":498,"expandedBytes":2333,"os":"avtech","sha256":"493d542698212372226ae1a22a3f834ea40b2b5ba3fdb8281583e524cb015c03"},{"definitions":4,"downloadBytes":554,"expandedBytes":2387,"os":"awplus","sha256":"ef1ea65ea89c5c883ae9618c95fbc7b730b61c7bb3e3a340e60ac9c2595e41ad"},{"definitions":4,"downloadBytes":565,"expandedBytes":2391,"os":"axos","sha256":"1e90ed2a46de5d92851898742ef3216557f6ef3da5048ea9794bc7cab5feb817"},{"definitions":7,"downloadBytes":630,"expandedBytes":3442,"os":"bats","sha256":"2e8c36df881f5411d52bfcd1500dda9f4224608972096c2baee1181c97c6144b"},{"definitions":4,"downloadBytes":734,"expandedBytes":2961,"os":"bdcom","sha256":"fe37667aca1253b030ee8fc13657488dc296b6b7b831b5c359425a4a4d022621"},{"definitions":1,"downloadBytes":471,"expandedBytes":993,"os":"bdt-flexstor","sha256":"968f14cf7962259701b0c51ce1e279bcd66f7b89ee5cc6c8bc2d99a602534424"},{"definitions":1,"downloadBytes":431,"expandedBytes":812,"os":"bison","sha256":"60fd7a4ded1ee198af9e0a68a0dc72524e82fc2391243264a74715b9e6396682"},{"definitions":5,"downloadBytes":517,"expandedBytes":2307,"os":"bke","sha256":"746c25122672cb7e08ffd8dd3285cbfe324bf5fd914769e770dbe5c2cd2a0694"},{"definitions":5,"downloadBytes":664,"expandedBytes":3708,"os":"bluecatnetworks","sha256":"0c1c9016349386f007513d9c59b3ff3fe97ddb14c211aba1fc690088de43e3ac"},{"definitions":1,"downloadBytes":460,"expandedBytes":962,"os":"broadworks","sha256":"1fde97788dcb8f251ebdbdf391ee39517691cfa40e62d974f9b482b559c3e6e9"},{"definitions":13,"downloadBytes":1603,"expandedBytes":11596,"os":"cat1900","sha256":"a202c39785aeb41356126e0f4096850523a2ad9a64cb398ff22c896732eafd82"},{"definitions":13,"downloadBytes":1598,"expandedBytes":11544,"os":"catos","sha256":"c52aef9a7b05163a9c54459d846b601a608d4f90df003c5d5327b542554ed9d3"},{"definitions":2,"downloadBytes":459,"expandedBytes":1162,"os":"cdata","sha256":"dc7ced48f5f4f2f2e9535bc979d7b52728ea0752b517296368546e1fd3569b7c"},{"definitions":4,"downloadBytes":583,"expandedBytes":2327,"os":"ceraos","sha256":"c9a38019c58eac21510dc1a6c5940462e6e9b3113cd3e8530a2641831daadef3"},{"definitions":1,"downloadBytes":442,"expandedBytes":829,"os":"chatsworth-pdu","sha256":"6ac1026678c04eaa391bfcb6d4c7291b3cb6e555e640ea1217ac1c7641be0c6d"},{"definitions":3,"downloadBytes":523,"expandedBytes":1814,"os":"ciena-rls","sha256":"a455d373a1ece2cf6068752874a77982aa5a6e4cdeb07308c293cde2ac4d5c6e"},{"definitions":4,"downloadBytes":910,"expandedBytes":4275,"os":"ciena-saos","sha256":"e17965b1612302778a55a3a272b04d91816e782dac0e7a77bb562d0691d6e1bc"},{"definitions":44,"downloadBytes":2406,"expandedBytes":32097,"os":"ciena-sds","sha256":"8a13338a668294f02e3be3b556ee3b26d670df7d8eca412110768c24199eba00"},{"definitions":22,"downloadBytes":2076,"expandedBytes":22186,"os":"cimc","sha256":"e9d2af96480ad609c39a3839e07aca5e193af94a5e800199f834d0bc8131c7cd"},{"definitions":1,"downloadBytes":466,"expandedBytes":1029,"os":"cirpack","sha256":"efd2304bb5f9e976a26d383f87932232e16e6aba75019e0d565484ccf456d38f"},{"definitions":13,"downloadBytes":1602,"expandedBytes":11622,"os":"ciscoepc","sha256":"e11221e77e138357450aff8cc92252df940c476d4a689f3227fb1552b76b8a8b"},{"definitions":13,"downloadBytes":1605,"expandedBytes":11700,"os":"ciscome1200","sha256":"24471b0e7648a8aaa5ae6778caf327192a4e0e093a02467dd6c5725a70d0abab"},{"definitions":1,"downloadBytes":452,"expandedBytes":876,"os":"ciscosat","sha256":"e6326f59398b82a5b18ae2c1c5d5fcd2ac2b180956fbbb33911cb15b997c56d8"},{"definitions":2,"downloadBytes":508,"expandedBytes":1694,"os":"ciscosb","sha256":"e1dce45a3f5c3da60de822cddbb352947dbc1be4c989a7e198ef991997d9f3d9"},{"definitions":13,"downloadBytes":1602,"expandedBytes":11622,"os":"ciscosce","sha256":"df12511f0ee7c8ba8a926a172a48b77ad7ec995baea8820546092ba2236ee245"},{"definitions":13,"downloadBytes":1602,"expandedBytes":11622,"os":"ciscospa","sha256":"0d67cf8df2209c1350e58938dfd2f48c7cfc661a0f604c5d3ec62c3886f95498"},{"definitions":13,"downloadBytes":1602,"expandedBytes":11622,"os":"ciscosrp","sha256":"66e3bca794e3fae8deec36772a42fa5c8e415dfa8c46d79625e7991cf5c7dda0"},{"definitions":1,"downloadBytes":494,"expandedBytes":1384,"os":"cnwave60","sha256":"7f4017c77b625de528639e58b9e17c16f3e3ae03a61770fc1f216
